version: '3'

services:
  apache:
    build:
      dockerfile: php7-apache2-dockerfile
      context: .
    container_name: php7-apache2
    restart: always
    ports:
      - '8088:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodledude
      - MYSQL_PASSWORD=moodlepass